# Sets a name for the application
spring.application.name=MedicalRecordMicroService-1

# Sets the server's port number
server.port=${MEDICAL_RECORD_SERVICE_PORT:2006}

# Sets the MongoDB connection URI for your database
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/OPD}

# ---- New Configuration for File Uploads ----
# Sets the maximum allowed file size for a single uploaded file.
# You can adjust this value (e.g., 50MB) depending on your needs.
spring.servlet.multipart.max-file-size=30MB

# Sets the maximum allowed size for the entire multipart request, including
# the file itself and all other form data.
spring.servlet.multipart.max-request-size=30MB
